import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./Header";
const outfit = Outfit({
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} antialiased overflow-x-hidden`} suppressHydrationWarning
      >
        <Header/>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
